import type { PublicEvidenceItem } from "@/lib/data/public-evidence";
import type { CopilotRequest, CopilotResponse, DataMode, ReleaseStatus } from "@/lib/schemas";
import { buildExtractiveCopilotResponse } from "./extractive";
import { buildCopilotPrompt, type GeneratedCopilotAnswer } from "./gemini-runtime";
import { retrieveEvidence } from "./retrieval";
import { validateGeneratedCitations } from "./runtime-generation";

interface CopilotReleaseContext {
  mode: DataMode;
  status: ReleaseStatus;
  totalEvidence: number;
}

export type CopilotGenerate = (prompt: string) => Promise<GeneratedCopilotAnswer>;

/**
 * Generative Copilot answer. The LLM authors only the prose `answer`; every typed
 * field (findings, sources, barriers, journeys, evidenceIds, metricLinks) is taken
 * from the deterministic extractive response, so the strict schema always validates
 * and citations are always a subset of what was retrieved.
 *
 * ANY failure — no ranked evidence, model error, off-topic (`relevant:false`) — returns
 * the untouched extractive response, so the Copilot degrades gracefully with no key.
 */
export async function buildGenerativeCopilotResponse(
  request: CopilotRequest,
  items: readonly PublicEvidenceItem[],
  datasetVersion: string,
  context: CopilotReleaseContext,
  generate: CopilotGenerate,
): Promise<CopilotResponse> {
  const base = buildExtractiveCopilotResponse(request, items, datasetVersion, context);

  // Abstention or no support: don't spend an LLM call, keep the extractive answer.
  if (!base.relevant || base.findings.length === 0) return base;

  const ranked = retrieveEvidence(request, items, 8).items;
  if (ranked.length === 0) return base;

  try {
    const prompt = buildCopilotPrompt(request.question, ranked, {
      mode: context.mode,
      totalEvidence: context.totalEvidence,
    });
    const generated = await generate(prompt);
    if (!generated.relevant || !generated.answer.trim()) return base;

    // Defensive: the citations we surface are ours, so this always passes — but it
    // guards against any future change that lets the model choose evidence IDs.
    validateGeneratedCitations(
      base.findings.flatMap((finding) => finding.evidenceIds),
      ranked.map((item) => item.evidenceId),
    );

    return {
      ...base,
      mode: "generated",
      usedLLM: true,
      answer: generated.answer.trim(),
      limitations: [
        `Answer generated by Gemini from ${ranked.length} retrieved public-safe evidence units; citations and typed fields are computed deterministically.`,
        context.mode === "provisional"
          ? "The release is provisional and its candidate labels are unreviewed; validate any claim in interviews."
          : "The answer is bounded by the active release and retrieval vocabulary.",
      ],
    };
  } catch {
    return base;
  }
}
